Create Mock API for Tasks and Account
Inholland-Hydroguard/mock-api pull request #22
Opened 2024-11-25 21:40 UTC by Jelleinholland

2024-11-25 22:27 UTC, TimV22 requested changes
Gaat de goede kant op, een paar kleine dingetjes en wat formatt issues.

2024-11-25 22:27 UTC, TimV22 commented on src/main/java/hydroguard/api/mock/models/reocurringTask/ReoccurringTasksDTO.java
Deze komt niet overeen met de andere qua format, Er is een default object voor dit soort dingen. GetMoreDTO, plants en measurements hebben deze geimplementeerd, kan je daar spieken.

2024-11-25 22:27 UTC, TimV22 commented on src/main/java/hydroguard/api/mock/models/reocurringTask/ReoccurringTaskDTO.java
> +    private int intervalSeconds;
Deze staat niet in de constructor, klopt dat? Ook niet in de get setters. Volgensmij komt hij daarom niet in de swagger tevoorschijn.

2024-11-25 22:27 UTC, TimV22 commented on src/main/java/hydroguard/api/mock/models/account/AccountsDTO.java
> Deze komt niet overeen met de andere qua format, Er is een default object voor dit soort dingen. GetMoreDTO, plants en measurements hebben deze geimplementeerd, kan je daar spieken.

2024-11-25 22:27 UTC, TimV22 commented on src/main/java/hydroguard/api/mock/models/task/TasksDTO.java
> Deze komt niet overeen met de andere qua format, Er is een default object voor dit soort dingen. GetMoreDTO, plants en measurements hebben deze geimplementeerd, kan je daar spieken.

2024-11-25 22:27 UTC, TimV22 commented on src/main/java/hydroguard/api/mock/controllers/account/AccountController.java
> +    public AccountsDTO getAllAccounts(
Get all voor accounts is niet voor normale users of heeft te veel info, denk je niet? Want waarom zou ik van iemand anders kunnen zien wat hun phone number is? In principe wil je hier alleen terughebben: Id, Username en avatarUrl. Misschien nog email, maar zou niet helemaal weten waarom.

2024-11-25 22:27 UTC, TimV22 commented on src/main/java/hydroguard/api/mock/controllers/account/AccountController.java
> +    @PostMapping
Post route zou wel nuttig kunnen zijn voor "Anonymous" users, maar in principe gaat het normale aanmaken van een user via keycloak. En als we hem gebruiken voor die Anonymous users dan zou er niet heel veel informatie nodig zijn in de post.

2024-11-28 10:35 UTC, TimV22 commented on src/main/java/hydroguard/api/mock/controllers/account/AccountController.java
> +@RequestMapping("/accounts")
Mis de /api prefix nog, had ik vorige keer over het hoofd gezien.

2024-11-28 10:35 UTC, TimV22 commented on src/main/java/hydroguard/api/mock/controllers/reoccurringtask/ReoccurringTaskController.java
> +@RequestMapping("/reoccurring-tasks")
> Mis de /api prefix nog, had ik vorige keer over het hoofd gezien.

2024-11-28 10:35 UTC, TimV22 commented on src/main/java/hydroguard/api/mock/controllers/tasks/TaskController.java
> +@RequestMapping("/tasks")
> Mis de /api prefix nog, had ik vorige keer over het hoofd gezien.

2024-11-28 11:17 UTC, Jelleinholland commented on src/main/java/hydroguard/api/mock/controllers/account/AccountController.java
> +@RequestMapping("/accounts")
oh shi your right oops. scherp van je

2024-11-29 12:41 UTC, TimV22 approved these changes

2024-11-29 12:43 UTC, CaptainJeppie commented on src/main/java/hydroguard/api/mock/controllers/account/AccountController.java
> +            @RequestParam(required = false) String name,
is name het enigste waar je op kan filteren

2024-11-29 12:46 UTC, CaptainJeppie commented on src/main/java/hydroguard/api/mock/models/reocurringTask/ReoccurringTaskDTO.java
> +    private boolean completed;
is niet beter om voor boolean iscompleted te doen

2024-11-29 12:46 UTC, CaptainJeppie commented on src/main/java/hydroguard/api/mock/models/task/TaskDTO.java
> +    private boolean completed;
same thing isCompleted

2024-11-29 12:47 UTC, CaptainJeppie commented on src/main/java/hydroguard/api/mock/controllers/reoccurringtask/ReoccurringTaskController.java
> +package hydroguard.api.mock.controllers.reoccurringtask;
zou je reoccuring taskcontrollen en taskcontroller niet in hetzelfde mapje doen. omdat dat bij dezelfde microservice hoort. hetzelfde voor de models daarvan

2024-11-29 12:48 UTC, CaptainJeppie commented on src/main/java/hydroguard/api/mock/controllers/reoccurringtask/ReoccurringTaskController.java
> +            @RequestParam(defaultValue = "1") int page,
zou je niet nog willen filteren op dueat

2024-11-29 12:49 UTC, CaptainJeppie commented on src/main/java/hydroguard/api/mock/controllers/tasks/TaskController.java
> +            @RequestParam(defaultValue = "10") int pageSize,
hetzelfde zou je niet op due_at willen filteren

2024-11-29 13:11 UTC, CaptainJeppie approved these changes
top

2024-11-29 13:11 UTC, merged